

import type { Metadata } from "next";
import { poppins, rubik } from "@/lib/fonts";
import "./globals.css"

import ReduxProvider from "@/Provider/ReduxPresistProbider/ReduxPresistProbider"
import Navbar from "@/Components/Header/Navbar";
import Footer from "@/Components/Footer/Footer";
import SessionWrapper from "@/Components/SessionWrapper/SessionWrapper";
import ToastProvider from "@/Components/ToastProvider/ToastProvider";

export const metadata: Metadata = {
  title: "E-bazaar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${rubik.variable} relative dark:bg-gray-900`}

      >

        <SessionWrapper>
          <ReduxProvider>
            <Navbar />
            {children}
            <ToastProvider />
            <Footer />
          </ReduxProvider>
        </SessionWrapper>



      </body>
    </html>
  );
}
