

import type { Metadata } from "next";
import { Poppins,Rubik } from "next/font/google";
import "./globals.css";
// import { Provider } from "react-redux";
// import { store } from "../redux/store";
import ReduxProvider from "./Provider/ReduxProvider/ReduxProvider";
import Layout from "./Components/Layout/Layout";


export const poppins = Poppins({
  weight: ['400', '500', '600', '700', '800'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
});
export const rubik = Rubik({
  weight: ['400', '500', '600', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-rubik',
});

export const metadata: Metadata = {
  title: "E-bazaar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${rubik.variable}`}
      >
        <ReduxProvider>
          <Layout>
            {children}
          </Layout>
        </ReduxProvider>


      </body>
    </html>
  );
}
