

import type { Metadata } from "next";
import { Poppins, Rubik } from "next/font/google";
import "./globals.css";
import ReduxProvider from "./Provider/ReduxProvider/ReduxProvider";

import Navbar from "./Components/Header/Navbar";
import Footer from "./Components/Footer/Footer";


export const poppins = Poppins({
  weight: ['400', '500', '600', '700', '800'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
});
export const rubik = Rubik({
  weight: ['400', '500', '600', '700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-rubik',
});

export const metadata: Metadata = {
  title: "E-bazaar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} ${rubik.variable} text-white`}
        style={{ background: "radial-gradient(125% 125% at 50% 100%, #000000 40%, #350136 100%)",}}
      >

        <ReduxProvider>
          <Navbar />
          {children}
          <Footer />
        </ReduxProvider>


      </body>
    </html>
  );
}
